# Generated by Django 3.2.6 on 2021-09-22 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_alter_profiles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('street_address', models.CharField(blank=True, max_length=254, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=25, null=True)),
                ('zip_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
