# Generated by Django 3.2.6 on 2021-08-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('hide_product', models.BooleanField(default=False)),
                ('on_special', models.BooleanField(default=False)),
                ('hot_tag', models.BooleanField(default=False)),
                ('original_tag', models.BooleanField(default=False)),
                ('selling_fast_tag', models.BooleanField(default=False)),
                ('add_to_banner', models.BooleanField(default=False)),
                ('new_tag', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='store.category')),
            ],
        ),
    ]
