# Generated by Django 3.2.6 on 2021-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210902_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_to_banner',
        ),
        migrations.AddField(
            model_name='product',
            name='add_to_popular_products',
            field=models.BooleanField(default=True),
        ),
    ]
