# Generated by Django 3.2.6 on 2021-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=254)),
                ('recipients_list', models.CharField(max_length=254)),
                ('email_subject', models.CharField(max_length=254)),
                ('message', models.TextField(max_length=1024)),
                ('email_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
