# Generated by Django 3.2.6 on 2021-10-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='recipients_list',
            new_name='recipient_list',
        ),
    ]
