# Generated by Django 3.2.6 on 2021-10-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_rename_recipients_list_contact_recipient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recipient_list',
            field=models.EmailField(max_length=254),
        ),
    ]
