from django.urls import path
from . import views

urlpatterns = [
     path('', views.display_homepage, name='home'),
     path('store/', views.products, name='products'),
     path('<int:product_id>/', views.single_product, name='single_product'),
     path('search/', views.search_result, name='search_result'),
     path('store/add/', views.add_product, name='add_product'),
     path('store/update/<int:product_id>/',
          views.update_product, name='update_product'),
     path('store/delete_warning/<int:product_id>/',
          views.delete_warning, name='delete_warning'),
     path('store/delete_product/<int:product_id>/',
          views.delete_product, name='delete_product'),
     path('store/hidden_products/',
          views.hidden_products, name='hidden_products'),
     path('store/out_of_stock_products/',
          views.out_of_stock_products, name='out_of_stock_products'),
     path('store/best_sellers/',
          views.best_sellers, name='best_sellers'),
     path('store/contact_page/',
          views.contact_page, name='contact_page'),
     path('store/original_gallery/',
          views.original_gallery, name='original_gallery'),
     path('store/accessories/',
          views.accessories, name='accessories'),
     path('store/paint_by_numbers/',
          views.paint_by_numbers, name='paint_by_numbers'),
     path('store/about_page/',
          views.about_page, name='about_page'),
     ]
