# Generated by Django 3.2.6 on 2021-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='buyer_name',
            field=models.CharField(default=models.CharField(max_length=60), max_length=60),
        ),
    ]
