# Generated by Django 3.2.6 on 2021-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkoutorder_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='deliver_to_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='buyer_name',
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
