# Generated by Django 3.2.6 on 2021-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='order_pid',
            field=models.CharField(editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='order_trolley',
            field=models.TextField(default='', max_length=1024, null=True),
        ),
    ]
