# Generated by Django 3.2.6 on 2021-09-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210922_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_pid',
            field=models.CharField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_trolley',
            field=models.TextField(default=''),
        ),
    ]
