# Generated by Django 3.2.6 on 2021-09-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210922_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
