# Generated by Django 3.2.6 on 2021-09-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210922_2252'),
        ('checkout', '0010_checkoutorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='profiles.profile'),
        ),
    ]
