# Generated by Django 3.2.6 on 2021-09-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0013_alter_checkoutorder_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='profile',
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
