# Generated by Django 3.2.6 on 2021-09-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_user'),
        ('checkout', '0015_auto_20210924_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_orders', to='profiles.profile'),
        ),
    ]
