# Generated by Django 3.2.6 on 2021-09-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_checkoutorder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='phone_number',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
