# Generated by Django 3.2.6 on 2021-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_checkoutorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='phone_number',
            field=models.CharField(default='', max_length=254),
        ),
    ]
