# Generated by Django 3.2.6 on 2021-10-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_alter_checkoutorder_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
